name: Test & CI / Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -q

  deploy:
    name: Package & Deploy (only if tests pass)
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Prepare Lambda zip
        run: |
          rm -f terraform/lambda.zip
          cd src
          zip -r ../terraform/lambda.zip . -x "__pycache__/*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Lambda zip to S3
        # This step uploads the lambda zip to a specified S3 bucket (pre-existing)
        env:
          S3_BUCKET: ${{ secrets.LAMBDA_S3_BUCKET }}
        run: |
          if [ -z "${S3_BUCKET}" ]; then
            echo "LAMBDA_S3_BUCKET secret not set. Exiting."
            exit 1
          fi
          KEY="lambda-${{ github.sha }}.zip"
          aws s3 cp terraform/lambda.zip "s3://${S3_BUCKET}/${KEY}"
          echo "Uploaded to s3://${S3_BUCKET}/${KEY}"
          echo "s3_key=${KEY}" >> $GITHUB_OUTPUT
        id: upload

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"

      - name: Terraform Init
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          TF_VAR_s3_lambda_bucket: ${{ secrets.LAMBDA_S3_BUCKET }}
          TF_VAR_s3_lambda_key: ${{ steps.upload.outputs.s3_key }}
          TF_VAR_store_ssm_json: ${{ secrets.STORE_SSM_JSON }}
          TF_VAR_store_json: ${{ secrets.STORE_JSON }}
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          TF_VAR_s3_lambda_bucket: ${{ secrets.LAMBDA_S3_BUCKET }}
          TF_VAR_s3_lambda_key: ${{ steps.upload.outputs.s3_key }}
          TF_VAR_store_ssm_json: ${{ secrets.STORE_SSM_JSON }}
          TF_VAR_store_json: ${{ secrets.STORE_JSON }}
        run: terraform apply -input=false -auto-approve tfplan